---
- name: cokolwiek
  hosts: prod
  become: yes
  become_method: sudo 

  vars:
    firewall_pkg: firewalld
    firewall_svc: firewalld
    web_pkg: httpd
    web_svc: httpd
    ssl_pkg: mod_ssl
    httpdconf_src: files/index.html
    httpdconf_dest: /var/www/html/index.html
  tasks:
    - name: Required packages are up to date
      dnf:
        name:
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
        state: latest
    - name: Ensure that {{ firewall_svc }} is running
      service:
        name: "{{ firewall_svc }}"
        state: started
        enabled: yes

    - name: Add {{ web_svc }} rule to {{ firewall_svc }}
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: true
    - name: Provide new index for {{ web_svc }}
      copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_dest }}"
    - name: Change content of index
      copy:
        content: "{{ ansible_facts['fqdn'] }} ({{ ansible_facts['default_ipv4'] ['address'] }}) have been customized by Ansible. \n "
        dest: "{{ httpdconf_dest }}"

    - name: Restart {{ web_svc }}
      service:
        name: "{{ web_svc }}"
        state: restarted
        enabled: yes

- name: Check service status
  hosts: localhost
  tasks:
    - name: Curl webservice on prod hosts
      uri:
        url: http://ans1
        return_content: yes
        status_code:
          - 200
      register: web_test
    - debug:
        var: web_test.content


      
