- name: Playbook control lab
  hosts: prod
  vars_files: vars.yml
  tasks:
    #Failed Message
    - name: Show failed System requirements message
      fail:
        msg: "The {{ inventory_hostname }} did not meet minimum reqs."
      when: >
        ansible_memtotal_mb < min_ram_mb or
        ansible_distribution != "Fedora"
    - name: Ensure required packages are installed
      dnf:
        name: "{{ packages }}"
        state: latest
    - name: ensure that all services are started and enabled
      service: 
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
    - name: Copy config files
      copy:
        src: "{{ src }}"
        dest: "{{ dest }}"
      notify: restart webservice
    - name: Configure firewall
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      loop:
        - http
        - https
  handlers:
    - name: restart webservice
      service:
        name: httpd
        state: restarted
