---
- name: Setup new host
  hosts: all
  become: true
  vars:
    # ansible_user: ansible_usr
    ansible_port: "2229"
    ansible_become_method: sudo
  vars_files:
    - secrets.yml
    - users.yml
  tasks:
    - name: Create users
      ansible.builtin.include_role:
        name: role_users
#    - name: Set hostname
#      ansible.builtin.hostname:
#        name: "{{ inventory_hostname }}"
#
#
#    - name: "Create .ssh dir"
#      ansible.builtin.file:
#        path: /home/{{ remote_username }}/.ssh
#        state: directory
#        owner: "{{ remote_username }}"
#        group: "{{ remote_username }}"
#        mode: '0700'
#
#    - name: "Provide authorized_keys for ansible user"
#      ansible.builtin.copy:
#        src: files/authorized_keys
#        dest: /home/{{ remote_username }}/.ssh/authorized_keys
#        mode: '0700'
#        owner: "{{ remote_username }}"
#        group: "{{ remote_username }}"
#
#    - name: "Allow admin users to sudo without a password (Fedora/CentOS)"
#      ansible.builtin.lineinfile:
#        dest: "/etc/sudoers" # path: in version 2.3
#        state: "present"
#        regexp: "^#%wheel"
#        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
#
#    - name: "Disable Selinux on host"
#      ansible.posix.selinux:
#        state: disabled
#
#    - name: "Update host (Fedora/CentOS)"
#      ansible.builtin.package:
#        name: "*"
#        state: latest
#        update_only: true
#      tags: update
#
#    - name: Setup alternate SSH port
#      ansible.builtin.lineinfile:
#        dest: "/etc/ssh/sshd_config"
#        regexp: "^Port"
#        line: "Port 2229"
#      notify: Restart sshd service and firewall (Fedora/CentOS)
#
#    - name: Add new ssh port to firewall (Fedora/CentOS)
#      ansible.posix.firewalld:
#        port: 2229/tcp
#        state: enabled
#        permanent: true
