---
- name: Setup new host
  hosts: all
  become: true
  # vars:
  # port used for debug  ansible_port: "2229"
  vars_files:
    - users.yml
  tasks:
    - name: Create users
      ansible.builtin.include_role:
        name: role_users
        apply:
          tags:
            - users
      tags: always

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Setup ssh service
      ansible.builtin.include_role:
        name: role_ssh
        apply:
          tags:
            - ssh
      tags: always
