---
- name: Setup new host
  hosts: all
  become: true
  vars:
    # ansible_user: ansible_usr
    ansible_port: "2229"
    ansible_become_method: sudo
  vars_files:
    - secrets.yml
    - users.yml
  tasks:
    - name: Create users
      ansible.builtin.include_role:
        name: role_users

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Setup ssh service
      ansible.builtin.include_role:
        name: role_ssh

#    - name: "Disable Selinux on host"
#      ansible.posix.selinux:
#        state: disabled
#
#    - name: "Update host (Fedora/CentOS)"
#      ansible.builtin.package:
#        name: "*"
#        state: latest
#        update_only: true
#      tags: update
#
#    - name: Setup alternate SSH port
#      ansible.builtin.lineinfile:
#        dest: "/etc/ssh/sshd_config"
#        regexp: "^Port"
#        line: "Port 2229"
#      notify: Restart sshd service and firewall (Fedora/CentOS)
#
#    - name: Add new ssh port to firewall (Fedora/CentOS)
#      ansible.posix.firewalld:
#        port: 2229/tcp
#        state: enabled
#        permanent: true
