---
- name: Setup new host
  hosts: all
  become: true
  vars:
    ansible_port: "2229"
    ansible_become_method: sudo
  vars_files:
    - secrets.yml
    - users.yml
  tasks:
    - name: Create users
      ansible.builtin.include_role:
        name: role_users

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Setup ssh service
      ansible.builtin.include_role:
        name: role_ssh
      # vars:
      #   role_ssh_sshport: 2230

#    - name: "Disable Selinux on host"
#      ansible.posix.selinux:
#        state: disabled
#
#    - name: "Update host (Fedora/CentOS)"
#      ansible.builtin.package:
#        name: "*"
#        state: latest
#        update_only: true
#      tags: update
#
