- name: Ensure that docker is configured
  hosts: localhost
  gather_facts: no
  become: yes
  vars:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
    - docker-compose-plugin
  tasks:
    - name: Add docker repository
      shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Ensure that required docker packages are installed
      dnf:
        name: "{{ pkg }}"
        state: latest  

    - name: Update docker compose module
      shell: ansible-galaxy collection install community.docker
    
    - name: Enable docker service
      service:
        name: docker
        state: started
        enabled: yes