---
- name: create user on all hosts
  hosts: servers
  become: true
  vars_files:
    - secret.yml
  tasks:
    - name: create user account on servers
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"