---
- name: mariadb server is running
  hosts: dev
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
  tasks:
    - name: Mariadb packages ares installed
      dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ mariadb_packages }}"
      when: ansible_distribution == "Centos"
    - name: start mariadb server
      service:
        name: mariadb
        state: started
        enabled: true
      when: ansible_distribution == "Centos"
