version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    dns:
      - 1.1.1.1
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: ''
      VIRTUAL_HOST: 'docker.pihole'
      SERVER_IP: '192.168.0.180'
      DNSMASQ_LISTENING: "local"
      WEB_PORT: '83'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
