---
- name: Init setup
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Load PACKAGES role (Fedora/CentOS)
    include_role:
      name: packages_role
      apply:
        tags:
          - packages
    tags: always
    when: ansible_facts['distribution'] == "Fedora" or 
          ansible_facts['distribution'] == "CentOS"

  - name: Load MOTD role
    include_role:
      name: motd_role
      apply:
        tags:
        - motd
    tags: never

  - name: Load NEOFETCH role
    include_role:
      name: neofetch_role
      apply:
        tags:
        - neofetch
    tags: always
    
  - name: Load DOCKER role (Fedora/CentOS)
    include_role:
      name: FC_docker_role
      apply:
        tags:
        - docker
    tags:
      - always

    when: ansible_facts['distribution'] == "Fedora" or 
          ansible_facts['distribution'] == "CentOS"

  - name: Load DOCKER role Ubuntu
    include_role:
      name: U_docker_role
      apply:
        tags:
        - docker
    tags:
      - always
    when: ansible_facts['distribution'] == "Ubuntu"
      
  - name: Load VIM role (Fedora/CentOS)
    include_role:
      name: FC_vim_role
      apply:
        tags:
        - vim
    tags:
      - always
    when: ansible_facts['distribution'] == "Fedora" or 
          ansible_facts['distribution'] == "CentOS"
