---
- name: test changed when option
  hosts: localhost
  gather_facts: no
  vars:
    additional_bridge: true
    bridge_name: int_bridge
  tasks:
    - name: Check if {{ bridge_name }} is active
      shell: nmcli connection show --active |grep int | awk '{print $1}'
      register: nmcli_command_result
      when: additional_bridge is true

    - name: Start internal bridge
      command:
        cmd: nmcli con up int_bridge
      when: 
        - additional_bridge is true  
        - bridge_name not in nmcli_command_result.stdout
    
    - name: Ensure that vms are running
      community.libvirt.virt:
        name: "{{ item }}"
        state: running
      with_inventory_hostnames:
        - infra