- name: configure network
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
  tasks:

  - name: setup bridge
    nmcli:
      type: bridge
      conn_name: bridge01
      ifname: br01
      ip4: "192.168.0.223/24"
      method4: manual
      method6: disabled
      gw4: "192.168.0.1"
      dns4: "192.168.0.170"
      state: present
      autoconnect: true

  - name: create bridge slave
    nmcli:
      type: bridge-slave
      conn_name: bridge01_slave
      ifname: enp1s0
      master: br01
      state: present
      hairpin: false
      autoconnect: yes

  - name: disable previous connection
    nmcli:
      conn_name: enp1s0
      state: present
      autoconnect: no

  - name: disable unnecessarry firewall entries
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: disabled
    with_items:
     - "1025-65535/tcp"
     - "1025-65535/udp"

  - name: enable 2229/tcp port for sshd
    firewalld:
      port: "2229/tcp"
      permanent: yes
      state: enabled

  - name: restart firewall service
    service:
      name: firewalld
      state: restarted
      enabled: yes

  - name: change ssh listen port
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#Port*'
      line: Port 2229