services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: plain-proxy
    network_mode: bridge
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./kontenery/nginx/data:/data
      - ./kontenery/nginx/letsencrypt:/etc/letsencrypt
