---
# tasks file for docker_role
- name: Add docker repository Fedora
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  when: ansible_facts['distribution'] == "Fedora"
  changed_when: my_output.rc != 0

- name: Install yum-utils package CentOS
  ansible.builtin.package:
    name: yum-utils
    state: present
  when: ansible_facts['distribution'] == "CentOS"

- name: Add docker repository CentOS
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_facts['distribution'] == "CentOS"
  changed_when: my_output.rc != 0

- name: Install docker packages
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: present
  tags: docker
  register: install

- name: Update docker compose module
  ansible.builtin.command: ansible-galaxy collection install community.docker
  tags: docker
  changed_when: my_output.rc != 0

- name: Enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags: docker
