@version: 4.10
@include "scl.conf"

source s_local {
	system();
	internal();
};

filter f_authpriv {
	facility(auth, authpriv);
};
filter f_cron {
	facility(cron);
};
filter f_iptables {
	match("IN=" value("MESSAGE")) and match("OUT=" value("MESSAGE"));
};
filter f_messages {
	level(info..warn) and not facility(auth, authpriv, mail, news, cron) and not program(syslog-ng) and not filter(f_iptables);
};

destination d_remote {
	network("10.66.66.10"
		port(514)
		transport(tcp)
		spoof-source(yes)
	);
};
destination d_secure {
	file("/var/log/secure");
};
destination d_messages_local {
	file("/var/log/messages");
};
destination d_cron_local {
	file("/var/log/cron");
};
destination d_all_local {
	file("/var/log/all");
};

options {
	chain_hostnames(off);
	create_dirs(no);
	dns_cache(no);
	flush_lines(0);
	group("log");
	keep_hostname(yes);
	log_fifo_size(10000);
	perm(0640);
	stats(freq(0));
	time_reopen(10);
	use_dns(no);
	use_fqdn(no);
};

log {
	source(s_local);
	destination(d_remote);
};

log {
	source(s_local);
	filter(f_authpriv);
	destination(d_secure);
};

log {
	source(s_local);
	filter(f_cron);
	destination(d_cron_local);
};

log {
	source(s_local);
	filter(f_messages);
	destination(d_messages_local);
};

log {
	source(s_local);
	destination(d_all_local);
};
