vms:
  hosts:
    ansible-debian:
      ansible_host: 192.168.122.10
      ansible_user: root
    ansible-almalinux:
      ansible_host: 192.168.122.11
      ansible_user: root

  children:
    debian_hosts:
      hosts:
        ansible-debian:
    rhel_hosts:
      hosts:
        ansible-almalinux:
