---
- name: Configure new hosts
  hosts: vms
  gather_facts: smart
  become: true
  become_user: root
  tasks:
    - name: Setup users
      ansible.builtin.include_role:
        name: role_users

    - name: Setup bash profile
      ansible.builtin.include_role:
        name: role_bash

    - name: Configure ssh service
      ansible.builtin.include_role:
        name: role_ssh
      when: not (role_ssh_skip_task | default(false))

    - name: Setup wireguard
      ansible.builtin.include_role:
        name: role_wireguard
      tags: wireguard

    - name: Configure logs
      ansible.builtin.include_role:
        name: role_rsyslog

#
#    - name: Configure backup scripts
#
#    - name: Update host
#
    - name: Install docker service
      ansible.builtin.include_role:
        name: role_docker
      tags: docker
#
#    - name: Start services
# - name: Cleanup
# usunięcie inituser
