---
- name: Ensure firewalld is installed
  dnf:
    name: firewalld
    state: present

- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Wait for firewalld to be ready
  wait_for:
    timeout: 5
  changed_when: false

- name: Open port 2229 for SSH
  ansible.posix.firewalld:
    port: "2229/tcp"
    permanent: true
    state: enabled
    immediate: yes

- name: Open port 51820/udp for WireGuard
  ansible.posix.firewalld:
    port: "51820/udp"
    permanent: true
    state: enabled
    immediate: yes

- name: Disable SSH service (port 22)
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: disabled
    immediate: yes
