# Enable UDP reception
module(load="imudp")
input(type="imudp" port="514")

# Skip logs from localhost (jawor.vpn or jawor)
if $fromhost == "jawor.vpn" or $fromhost == "jawor" or $fromhost-ip == "127.0.0.1" or $fromhost-ip == "10.66.66.1" then {
    stop
}
