---
- name: Set SELinux to permissive
  command: setenforce 0
  changed_when: true

- name: Configure SELinux permissive in config file
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
    create: yes
    mode: '0644'
