---
# tasks file for docker_role
- name: debug os distro
  debug:
    var: ansible_facts['distribution']
  tags: docker

- name: add repo
  yum_repository:
    name: docker_repo
    description: Repository for docker related packages
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
  tags: docker
  when: ansible_facts['distribution'] == "Fedora" 
  
- name: Install docker packages
  dnf:
    name: "{{ docker_packages }}"
    state: latest
  tags: docker
  register: install
  ignore_errors: "{{ __ignore | default(false) }}"

- name: failure test
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  when: install.failed

- name: Install docker packages
  dnf:
    name: "{{ docker_packages }}"
    state: latest
  tags: docker
  register: install
  when: install.failed

- name: Update docker compose module
  shell: ansible-galaxy collection install community.docker
  tags: docker
  
- name: Enable docker service
  service:
    name: docker 
    state: started
    enabled: yes
  tags: docker