---
- name: Use role to enforce selinux on affected hosts
  hosts: all
  vars:
    selinux_state: enforcing
    selinux_policy: targeted
  tasks: 
    - name: Execute role and catch errors
      block:
        - name: Include role
          include_role:
            name: linux-system-roles.selinux
      rescue:
        - name: Handle errors
          fail:
            msg: 'role failed'
          when: not selinux_reboot_required

        - name: Restart managed host
          reboot:

        - name: Wait for connection
          wait_for_connection:
            delay: 10
            timeout: 300

        - name: Reaply role
          include_role:
            name: linux-system-roles.selinux
