---
- name: enable intranet services
  hosts:
    - ans1
  become: yes
  tasks:
    - name: install latest version of httpd and firewalld
      dnf:
        name:
          - httpd
          - firewalld
        state: latest
    - name: test html page is installed
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
    - name: firewalld enabled and running
      service:
        name: firewalld
        state: started
        enabled: true
    - name: httpd enabled in firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: http service enabled and running
      service:
        name: httpd
        state: started
        enabled: true
- name: test if serice is enabled
  hosts:
    - ans2
  become: yes
  tasks:
    - name: Test serice on ans1
      uri:
        url: http://ans1
        return_content: yes
        status_code: 200

