# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = [workspace 1 silent] sleep 5 && omarchy-launch-browser
exec-once = [workspace 1 silent] sleep 5 && uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
exec-once = [workspace 3 silent] sleep 8 && omarchy-launch-editor
exec-once = sleep 8 && hyprctl dispatch exec [workspace 3 silent] omarchy-launch-webapp https://gemini.google.com/app
exec-once = sleep 11 && hyprctl dispatch exec [workspace 4 silent] omarchy-launch-webapp https://discord.com/channels/@me
exec-once = sleep 11 && hyprctl dispatch exec [workspace 4 silent] omarchy-launch-webapp https://web.whatsapp.com/
exec-once = [workspace 5 silent] sleep 14 && omarchy-launch-or-focus spotify
