# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = [workspace 4 silent] omarchy-launch-webapp https://discord.com/channels/@me
exec-once = [workspace 4 silent] omarchy-launch-webapp https://web.whatsapp.com/
exec-once = [workspace 5 silent] omarchy-launch-or-focus spotify
exec-once = [workspace 3 silent] omarchy-launch-tui opencode
exec-once = [workspace 3 silent] omarchy-launch-editor
exec-once = [workspace 1 silent] uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
exec-once = [workspace 1 silent] omarchy-launch-browser


