# Window rules for webapps that don't respect workspace in autostart
windowrule = workspace 3 silent, match:class chrome-gemini.google.com__app-Default
windowrule = workspace 4 silent, match:class chrome-discord.com__channels_@me-Default
windowrule = workspace 4 silent, match:class chrome-web.whatsapp.com__-Default