exec-once = [workspace 1 silent] sleep 5 && omarchy-launch-browser
exec-once = [workspace 3 silent] sleep 8 && omarchy-launch-editor
exec-once = sleep 8 && hyprctl dispatch exec [workspace 3 silent] claude-desktop
exec-once = sleep 8 && hyprctl dispatch exec [workspace 3 silent] steam
exec-once = sleep 11 && hyprctl dispatch exec [workspace 4 silent] discord
exec-once = sleep 11 && hyprctl dispatch exec [workspace 4 silent] omarchy-launch-or-focus-webapp WhatsApp https://web.whatsapp.com/
exec-once = [workspace 5 silent] sleep 14 && spotify
exec-once = ~/.local/bin/lid-handler-daemon.sh &
