server:
  http_listen_port: 9080  #Promtail listen port
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://212.127.78.121:3100/loki/api/v1/push  #Loki target instance

scrape_configs: #The most important part
- job_name: system
  static_configs:
  - targets:
      - localhost #Promtail target is localhost
    labels:
      instance: dworzec.jawor.com #Label identifier for instance (hostname -f)
      env: dworzec #Environment label
      job: secure #Job label
      __path__: /var/log/secure
