---
- name: Init setup
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Load PACKAGES role
    include_role:
      name: packages_role
      apply:
        tags:
          - packages
    tags: always

  - name: Load MOTD role
    include_role:
      name: motd_role
      apply:
        tags:
        - motd
    tags: never

  - name: Load NEOFETCH role
    include_role:
      name: neofetch_role
      apply:
        tags:
        - neofetch
    tags: always
    
  - name: Load DOCKER role
    include_role:
      name: docker_role
      apply:
        tags:
        - docker
    tags:
      - always
      
  - name: Load VIM role
    include_role:
      name: vim_role
      apply:
        tags:
        - vim
    tags:
      - always