---
- name: Init setup
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Load MOTD role
    include_role:
      name: motd_role
      apply:
        tags:
        - motd
    tags: always

  - name: Load DOCKER role
    include_role:
      name: docker_role
      apply:
        tags:
        - docker
    tags:
      - always
- name: Setup VIM
  become: no
  hosts: all
  gather_facts: true
  tasks:
  - name: Load VIM role
    include_role:
      name: vim_role
      apply:
        tags:
        - vim
    tags:
      - always