---

- name: Setup new host for next ansible playbooks
  hosts: all
  remote_user: root
  vars:
    - ansible_port: "22"
    - remote_username: "{{ inventory_hostname + '_' + 'user'}}"
  tasks:
    - name: Load INIT role (Fedora/CentOS)
      include_role:
        name: init_role_CENT_FEDORA
        apply:
          tags:
            - init
      tags: always
      when: ansible_facts['distribution'] == "Fedora" or 
            ansible_facts['distribution'] == "CentOS"

    - name: Load INIT role (Ubuntu)
      include_role:
        name: init_role_UBUNTU
        apply:
          tags:
            - init
      tags: always
      when: ansible_facts['distribution'] == "Ubuntu"
