role_users_remote_username: "{{ inventory_hostname + '_' + 'user' }}"

role_users_user_details:
  - username: "{{ role_users_remote_username }}"
    sudoers: true
  - username: ansible_user
    sudoers: true
  - username: test_user
