role_users_remote_username: "{{ inventory_hostname + '_' + 'user' }}"
admin_pubkey: |-
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDB1nmxZ10EKKGkLJyD1TyJdPIR9H
  pbxZV8AE3XPzXXSrOJj5ME8vNlQYrZ11YeG4G+Udq/0eZPzZfsq+yjqOhLID/LGfOAC7
  WJ7my0MV1mMmBZjwRvQqQbWsHsWsUMiZcQiKsMIRJxDbBzjNYvq8ZumFel5vwCmkKQS9
  2K0ImJ4lYyhwHHslQT7AT7aP99wCzVusUmQP7dcHX4V5Qwzq/V6cR+HVeD8SRc/S3EmF
  Sb86xN64pfyhsNyGmgmvD/IuhEKlOz058HogTVjPVNAAzQ9aY2ZE/Dq4Da4mjXZEHijp
  qBrod5bc0UrKB9Uo70++zdI5BvvqVIjjLYBE6FP4xix+mY8hwqKZ+NBHcfbWxnn0OABuR
  vqERJQMOAvD1BEW8afwC/SdP28nR6uVjBjbrLey/pPY35FBH8I9VUCJnuoFIH/COz82wC
  +11XgoFRuflBbeumb2hBgeXMWPmnF1sWQVkutTfoiKXRmt58lZ/4rGUIO0e/WXWHCh6ypG
  X+YaE= bjawo@Jawor-PC"
role_users_user_details:
  - username: "{{ role_users_remote_username }}"
    groups: wheel
    ssh_pubkey: "test-entry"
    sudoers: true
  - username: ansible_usr
    groups: ansible_usr
    sudoers: true
