
exec-once = [workspace 1 silent] sleep 5 && omarchy-launch-browser
#exec-once = [workspace 3 silent] omarchy-launch-webapp https://gemini.google.com/app
exec-once = [workspace 2 silent] sleep 3 && steam
exec-once = [workspace 4 silent] sleep 3 && discord
exec-once = [workspace 4 silent] omarchy-launch-or-focus-webapp https://web.whatsapp.com/
exec-once = [workspace 5 silent] sleep 14 && spotify