
exec-once = [workspace 1 silent] sleep 5 && omarchy-launch-browser
exec-once = [workspace 3 silent] steam
exec-once = [workspace 4 silent] discord
exec-once = [workspace 4 silent] omarchy-launch-or-focus-webapp https://web.whatsapp.com/
exec-once = [workspace 5 silent] sleep 14 && spotify