cursor {
    no_hardware_cursors = false
}

# Window rules for webapps that don't respect workspace in autostart
windowrule = workspace 3 silent, match:class chrome-gemini.google.com__app-Default
windowrule = workspace 4 silent, match:class chrome-discord.com__channels_@me-Default
windowrule = workspace 4 silent, match:class chrome-web.whatsapp.com__-Default

# Dim inactive windows and opacity
decoration {
    #inactive_opacity = 0.2
    dim_inactive = true
    dim_strength = 0.2
}

# Smooth animations
animations {
    enabled = yes

    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = smooth, 0.25, 0.1, 0.25, 1.0
    bezier = butter, 0.4, 0, 0.2, 1

    animation = windows,     1, 2, easeOutQuint
    animation = windowsIn,  1, 1.5, easeOutQuint, popin 80%
    animation = windowsOut, 1, 1, easeOutQuint, popin 80%
    animation = fade,        1, 3, butter
    animation = fadeIn,      1, 2, easeInOutCubic
    animation = fadeOut,     1, 2, easeInOutCubic
    animation = layers,      1, 2, easeOutQuint
    animation = layersIn,    1, 2, easeOutQuint, fade
    animation = layersOut,   1, 1, linear, fade
    animation = workspaces,   1, 2, easeOutQuint, fade
}